### ISSUE TITLE
Hacer links a papers más amigables

### ISSUE THREAD

**Issue by caredg** [pablobuitron/masterthesis#14]
@pablobuitron [aquí](https://github.com/pablobuitron/masterthesis/wiki#esta-es-la-wiki-del-proyecto-de-mi-tesis-de-maestr%C3%ADa), además que debería haber una sección de referencias, es muy complicado saber a qué paper se refiere.  Al menos deberías colobar cada link como, e.g.:
[Magnetic Disturbances preceding the 1964 Alaska Earthquake](https://www.semanticscholar.org/paper/Magnetic-Disturbances-preceding-the-1964-Alaska-Moore/6bad9f66845e4ff907a8bf97aa29fcd46567ec6f?sort=is-influential)

**Comment by pablobuitron** [comment]
Links más intuitivos.
Sección de referencias añadida.
