### ISSUE TITLE
Resolver problema de ángulo cenital fijo

### ISSUE THREAD

**Issue by caredg** [pablobuitron/masterthesis#15]
Recientemente se discutió que poner $\theta_1$ y $\theta_2$ con el mismo valor, e.g., cero, no daba el resultado esperado.  ¿Es esto cierto?  NOTA: Cualquier issue presentado para este tipo de problemas deberá venir acompañado de gráficos si es necesario para la discusión.

**Comment by pablobuitron** [comment]
Luego de hacer algunas pruebas, al fin se consiguió recuperar una simulación que tenga al menos una lluvia. Esto ayudó a identificar que, en efecto, el poner ambos ángulos iguales, se fija el ángulo.  
A continuación se muestra una simulación de un minuto de lluvia a 40°.
![60sec40deg](https://github.com/pablobuitron/masterthesis/assets/64674504/d01e0e4e-e2b2-4eba-959c-cddceeec4ebc)
Tal vez, la escogencia de 0° fijos al inicio era solo un error de límite y el ánglo debe ser siempre mayor, esto sería bueno explorar con más simulaciones sencillas, dejaré este issue abierto para seguir investigando al respecto.

**Comment by pablobuitron** [comment]
A continuación, muestro resultados obtenidos empleando el script de python [analisis.py](https://github.com/pablobuitron/masterthesis/blob/master/analisis.py) para esta simulación:
![Captura desde 2023-06-08 01-14-28](https://github.com/pablobuitron/masterthesis/assets/64674504/11929bc1-b5cc-4773-a00b-53fe254b9cb8)
![Captura desde 2023-06-08 01-15-03](https://github.com/pablobuitron/masterthesis/assets/64674504/2a14954a-a3bf-4ab8-905c-a7e376fe92cb)
Como la simulación es corta, al final al compilar, esta generó solo una lluvia.
