### ISSUE TITLE
Crear un template para el proceedings de ICRC2023 en Overleaf

### ISSUE THREAD

**Issue by caredg** [pablobuitron/masterthesis#21]
@caredg creará un template para el proceedings del ICRC2023 en Overleaf.  Deberá ser @caredg, con su versión del CERN de Overleaf, para poder tener la habilidad de que todos los autores puedan editar (en la versión gratis no es posible).

**Comment by pablobuitron** [comment]
He recibido ya una respuesta al mail enviado.  
Me dice que sí hay que hacer un proceedings, adjunto captura del mail:

![Image](https://github.com/pablobuitron/masterthesis/assets/64674504/e8acbe81-b7e6-4548-a857-e4b21f4816ad)

Este es [link](https://www.icrc2023.org/participate/#proceedings-submission) que envía en el mail.

**Comment by caredg** [comment]
Ok, estas son buenas noticias.  Siempre es bueno dejar récord del trabajo.... procederé con el objetivo de este issue y necesitaremos empezar a trabajar en él...

**Comment by caredg** [comment]
@pablobuitron he subido el template de Proceedings del ICRC 2023 en Overleaf.  Ambos deberíamos poder modificar el documento proyecto en este [link](https://www.overleaf.com/4546345758pfpjrgtdchkw). Guárdalo por favor.
