### ISSUE TITLE
Understand the plots

### ISSUE THREAD

**Issue by pablobuitron** [pablobuitron/masterthesis#9]
Find out why is the detection of the particles "invariant" with different configuration of the simulation.

**Comment by caredg** [comment]
@pablobuitron Here you can add the plots in order to remember what we are talking about.  For instance, those plots that show asymmetry and we did not understand should be here with a description of the discussion and the plant to tackle that.

**Comment by pablobuitron** [comment]
[Here](https://github.com/pablobuitron/masterthesis/tree/results), in the result's branch, are all the plots and code used to generate them. Soon I will edit this branch, having all the plots in a different directory. I'll add the issue.
![fluxquito1min0degkm](https://github.com/pablobuitron/masterthesis/assets/64674504/e0d1e98e-8f8d-4dd1-9374-901d66f6bfd2)
![fluxquito1min0degkm](https://github.com/pablobuitron/masterthesis/assets/64674504/dd84da24-b7c3-478d-9c73-8638420a677c)
![fluxquito3min90degkm](https://github.com/pablobuitron/masterthesis/assets/64674504/fd62cb50-7132-4814-bd73-bfb8831c9c64)
